# Generated by Django 4.2 on 2023-04-13 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stalk_market', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='island_name',
            field=models.TextField(max_length=10),
        ),
    ]
