# Generated by Django 4.2 on 2023-04-13 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stalk_market', '0002_alter_user_island_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.FileField(default='assets/default_profile_pic.jpg', max_length=255, upload_to='assets/profile_pics/'),
        ),
    ]
