# Generated by Django 4.2 on 2023-04-09 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stalk_market', '0002_alter_users_profile_picture'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comments',
            new_name='Comment',
        ),
        migrations.RenameModel(
            old_name='Posts',
            new_name='Post',
        ),
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
    ]
