# Generated by Django 4.2 on 2023-04-13 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stalk_market', '0003_alter_user_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=255),
        ),
    ]
