# Generated by Django 4.2 on 2023-04-09 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stalk_market', '0003_rename_comments_comment_rename_posts_post_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='island_name',
            field=models.CharField(max_length=10),
        ),
    ]
