# Generated by Django 4.2 on 2023-04-13 20:52

from django.db import migrations, models
import stalk_market.models


class Migration(migrations.Migration):

    dependencies = [
        ('stalk_market', '0004_alter_user_password_alter_user_username'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', stalk_market.models.CustomUserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
