# Generated by Django 4.2 on 2023-04-14 19:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stalk_market', '0005_alter_user_managers_alter_post_post_picture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='island_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='island_name_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_picture',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
