# Generated by Django 4.2 on 2023-04-14 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stalk_market', '0007_alter_post_island_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='island_name',
            field=models.CharField(default='', max_length=10),
        ),
    ]
